### ISSUE TITLE
Code Engine config.json 

### ISSUE THREAD

**Issue by greyhoundforty** [l2fprod/bxshell#5]
When trying to list Code Engine projects within bxshell the command is failing due to being unable to locate the config.json file:

```
$ ic ce project list
panic: open /root/.bluemix/plugins/code-engine/config.json: no such file or directory

goroutine 1 [running]:
github.com/IBM-Cloud/ibm-cloud-cli-sdk/plugin.(*pluginConfig).init.func1()
	/home/travis/gopath/pkg/mod/github.com/!i!b!m-!cloud/ibm-cloud-cli-sdk@v0.6.7/plugin/plugin_config.go:126 +0x75
sync.(*Once).doSlow(0xc000ad80b0, 0xc00010d720)
	/home/travis/.gimme/versions/go1.15.linux.amd64/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/home/travis/.gimme/versions/go1.15.linux.amd64/src/sync/once.go:57
github.com/IBM-Cloud/ibm-cloud-cli-sdk/plugin.(*pluginConfig).init(0xc00082c140)
	/home/travis/gopath/pkg/mod/github.com/!i!b!m-!cloud/ibm-cloud-cli-sdk@v0.6.7/plugin/plugin_config.go:123 +0x65
github.com/IBM-Cloud/ibm-cloud-cli-sdk/plugin.(*pluginConfig).Get(0xc00082c140, 0x18f5589, 0xb, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/!i!b!m-!cloud/ibm-cloud-cli-sdk@v0.6.7/plugin/plugin_config.go:135 +0x72
github.com/IBM-Cloud/ibm-cloud-cli-sdk/plugin.(*pluginConfig).GetStringWithDefault(0xc00082c140, 0x18f5589, 0xb, 0x0, 0x0, 0x79ac3f, 0xc00003b740, 0xc0008c0460, 0x19)
	/home/travis/gopath/pkg/mod/github.com/!i!b!m-!cloud/ibm-cloud-cli-sdk@v0.6.7/plugin/plugin_config.go:153 +0x49
github.com/IBM-Cloud/ibm-cloud-cli-sdk/plugin.(*pluginConfig).GetString(0xc00082c140, 0x18f5589, 0xb, 0x19, 0x1b08120, 0xc0000fc840, 0x0)
	/home/travis/gopath/pkg/mod/github.com/!i!b!m-!cloud/ibm-cloud-cli-sdk@v0.6.7/plugin/plugin_config.go:149 +0x47
github.ibm.com/coligo/cli/plugin.InitCommand(0x1b26de0, 0xc00082c180, 0x1b1c040, 0xc000ae43c0, 0x0)
	/home/travis/gopath/src/github.ibm.com/coligo/cli/plugin/init.go:97 +0xc12
github.ibm.com/coligo/cli/plugin.(*ColigoPlugin).Run(0xc0002d7730, 0x1b26de0, 0xc00082c180, 0xc000186160, 0x2, 0x2)
	/home/travis/gopath/src/github.ibm.com/coligo/cli/plugin/plugin.go:66 +0x2e5
github.com/IBM-Cloud/ibm-cloud-cli-sdk/plugin.StartWithArgs(0x1ad1aa0, 0xc0002d7730, 0xc000186160, 0x2, 0x2)
	/home/travis/gopath/pkg/mod/github.com/!i!b!m-!cloud/ibm-cloud-cli-sdk@v0.6.7/plugin/plugin_shim.go:35 +0x1ba
github.com/IBM-Cloud/ibm-cloud-cli-sdk/plugin.Start(...)
	/home/travis/gopath/pkg/mod/github.com/!i!b!m-!cloud/ibm-cloud-cli-sdk@v0.6.7/plugin/plugin_shim.go:15
main.main()
	/home/travis/gopath/src/github.ibm.com/coligo/cli/main.go:9 +0x85
```

It does not look like bxshell is creating the code-engine directory for the environment:

```
λ ls -l ~/.bxshell/environments/personal                                                                                                                                                      
total 24
-rw-------  1 ryan  staff  3522 Sep 22 12:15 bx-config.json
-rw-r--r--  1 ryan  staff   906 Sep 22 12:15 cf-config.json
drwxr-xr-x  2 ryan  staff    64 Sep  8 15:14 cloud-functions/
drwxr-xr-x  2 ryan  staff    64 Sep  8 15:14 container-registry/
drwxr-xr-x  3 ryan  staff    96 Sep  8 15:14 container-service/
drwxr-xr-x  2 ryan  staff    64 Sep  8 15:14 docker/
drwxr-xr-x  2 ryan  staff    64 Sep  8 15:14 helm/
-rw-r--r--  1 ryan  staff   177 Sep 22 12:15 slcli.conf
drwxr-xr-x  2 ryan  staff    64 Sep  8 15:14 softlayer/
drwxr-xr-x  3 ryan  staff    96 Sep  8 15:17 vpc-infrastructure/
-rw-r--r--  1 ryan  staff     0 Sep 22 12:15 wsk.props
```

**Comment by greyhoundforty** [comment]
Looks like I had not pulled the latest version of the bxshell repository. I see that it is now updated to include the mkdir code-engine command. Closing issue.
